from bitex.interface.extensions import Bitfinex
from bitex.interface.extensions import Bitstamp
from bitex.interface.extensions import Bittrex
from bitex.interface.extensions import Bter
from bitex.interface.extensions import CCEX
from bitex.interface.extensions import CoinCheck
from bitex.interface.extensions import Cryptopia
from bitex.interface.extensions import HitBTC
from bitex.interface.extensions import Kraken
from bitex.interface.extensions import OKCoin
from bitex.interface.extensions import Poloniex
from bitex.interface.extensions import QuadrigaCX
from bitex.interface.extensions import TheRockTrading
from bitex.interface.extensions import Vaultoro
