"""Supplies API modules."""
from bitex.api.base import BaseAPI
from bitex.api.REST import RESTAPI
from bitex.api.REST import BitfinexREST
from bitex.api.REST import BitstampREST
from bitex.api.REST import BittrexREST
from bitex.api.REST import CCEXREST
from bitex.api.REST import CoincheckREST
from bitex.api.REST import CryptopiaREST
from bitex.api.REST import GDAXREST
from bitex.api.REST import GeminiREST
from bitex.api.REST import HitBTCREST
from bitex.api.REST import ITbitREST
from bitex.api.REST import KrakenREST
from bitex.api.REST import OKCoinREST
from bitex.api.REST import PoloniexREST
from bitex.api.REST import QuadrigaCXREST
from bitex.api.REST import QuoineREST
from bitex.api.REST import RockTradingREST
from bitex.api.REST import VaultoroREST
from bitex.api.REST import YunbiREST
